/* File: src/app/authenticatedLayout.tsx */
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ToastContainer } from "react-toastify";
import { TwManageProvider } from './providers/TwManageProvider';
import Header from './components/Header';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function AuthenticatedLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TwManageProvider>
          <ToastContainer />
          <Header />
          {children}
        </TwManageProvider>
      </body>
    </html >
  )
}
