import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import ToastProvider from '@/app/providers/toast.provider'
// import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import { TwManageProvider } from './providers/TwManageProvider';
import { IGuild } from './interfaces/types';
import Page from './page'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  guild = null
}: {
  children: React.ReactNode
  guild?: IGuild | null
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TwManageProvider guild={guild}>
          <ToastContainer />
          {children}
        </TwManageProvider>
      </body>
    </html >
  )
}

