/* File: src/app/publicLayout.tsx */
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ToastContainer } from "react-toastify";
import { TwManageProvider } from './providers/TwManageProvider';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function PublicLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TwManageProvider>
          <ToastContainer />
          {children}
        </TwManageProvider>
      </body>
    </html>
  )
}


